global:
    imagePullSecrets: 
    - regcred

sense:
    ingress_available: true

    config:
        domain_name: ""
        org:
            name: ""
            admin_email: ""
        storage:
            bucket_name: ""
            bucket_service_account_json: ""
        db:
            hostname: ""
            port: ""
            database_name: ""
            username: ""
            password: ""
            ssl: ""
        email:
            sendgrid:
                enabled: "false"
                api_key: ""
            mailgun:
                enabled: "false"
                api_key: ""
            mailjet:
                enabled: "false"
                api_key: ""
            postmark:
                enabled: "false"
                api_key: ""
            smtp:
                enabled: "true"
                host: ""
                port: ""
                username: ""
                password: ""

    autolabel:
        registry: gcr.io
        repo: sense-artifacts/marketplace/autolabel
        tag: latest
    
    nextlabel:
        registry: gcr.io
        repo: sense-artifacts/marketplace/nextlabel
        tag: latest

    smartpoly:
        registry: gcr.io
        repo: sense-artifacts/marketplace/smartpoly
        tag: latest

    dashboard:
        registry: gcr.io
        repo: sense-artifacts/marketplace/dashboard
        tag: latest

    api:
        registry: gcr.io
        repo: sense-artifacts/marketplace/backend-api
        tag: fix

    migrator:
        registry: gcr.io
        repo: sense-artifacts/marketplace/migrator
        tag: latest
            