---
apiVersion: v1
kind: ConfigMap
metadata:
    name: sense-config
    namespace: {{ .Release.Namespace | default "sense" }}
data:
    DOMAIN_NAME: {{ .Values.sense.config.domain_name | default "" }}
    BUCKET_NAME: {{ .Values.sense.storage.bucket_name | default "" }}
    DB_HOST: {{ .Values.sense.config.db.hostname | default "" }}
    DB_PORT: {{ .Values.sense.config.db.port | default "" }}
    DB_NAME: {{ .Values.sense.config.db.name | default "" }}
    DB_USERNAME: {{ .Values.sense.config.db.username | default "" }}
    DB_PASSWORD: {{ .Values.sense.config.db.password | default "" }}
    DB_SSL: {{ .Values.sense.config.db.ssl | default "" }}
    {{ if eq .Values.sense.config.email.sendgrid.enabled "true" }}
    SENDGRID_API_KEY: {{ .Values.sense.config.email.sendgrid.api_key | default "" }}
    SENDGRID_HOSTNAME: "smtp.sendgrid.net"
    SENDGRID_PORT: "2525"
    {{ end }}
    {{ if eq .Values.sense.config.email.mailgun.enabled "true" }}
    MAILGUN_API_KEY: {{ .Values.sense.config.email.mailgun.api_key | default "" }}
    MAILGUN_HOSTNAME: "smtp.mailgun.org"
    MAILGUN_PORT: "2525"
    {{ end }}
    {{ if eq .Values.sense.config.email.mailjet.enabled "true" }}
    MAILJET_API_KEY: {{ .Values.sense.config.email.mailjet.api_key }}
    MAILJET_HOSTNAME: "in-v3.mailjet.com"
    MAILJET_PORT: "2525"
    {{ end }}
    {{ if eq .Values.sense.config.email.postmark.enabled "true" }}
    POSTMARK_API_KEY: {{ .Values.sense.config.email.postmark.api_key | default "" }}
    POSTMARK_HOSTNAME: ""
    POSTMARK_PORT: "2525"
    {{ end }}
    {{ if eq .Values.sense.config.email.smtp.enabled "true" }}
    SMTP_HOST: {{ .Values.sense.config.email.smtp.host | default "" }}
    SMTP_PORT: {{ .Values.sense.config.email.smtp.port | default "" }}
    SMTP_USERNAME: {{ .Values.sense.config.email.smtp.username | default "" }}
    SMTP_PASSWORD: {{ .Values.sense.config.email.smtp.password | default "" }}
    {{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: sense-init
    namespace: {{ .Release.Namespace | default "sense" }}
data:
    ORGANIZATION_NAME: {{ .Values.sense.config.org.name | default "" }}
    ORGANIZATION_ADMIN_EMAIL: {{ .Values.sense.config.org.admin_email | default "" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: autolabel
    namespace: {{ .Release.Namespace | default "sense" }}
data:
    AUTOLABEL_SERVICE_PORT: "5000"
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: accounts
    namespace: sense
data:
    SQL_DATABASE: sense
    SQL_HOST: "sense-postgres.{{ .Release.Namespace | default "sense" }}.svc.cluster.local"
    SQL_PORT: "5432"
    SSL_EXTRA: enabled
    AUTH_HANDLER_URL: ""
    NODE_ENV: production
    HUBSPOT_PORTAL_ID: ""
    HUBSPOT_FORM_ID: ""
    ENVIRONMENT: ""
    PUBSUB_TOPIC_PREFIX: ""
    NEW_RELIC_APP_NAME: ""
    APP_URL: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: api
    namespace: sense
data:
    SENSE_INGRESS_GRPC_PORT: "9090"
    SENSE_INGRESS_LOGGER_JSON: "true"
    LOGGER_LEVEL: "info"
    SENSE_INGRESS_BLOB_ENABLED_STORES: "gcs"
    SENSE_INGRESS_BLOB_DEFAULT_STORE: "gcs"
    SENSE_INGRESS_BLOB_GCS_STORE_UPLOAD_BUCKET: "{{ .Values.global.bucketName }}/backendApi/upload/"
    SENSE_INGRESS_PORT: "5005"
    SENSE_INGRESS_TRACE_ERROR: "false"
    SENSE_INGRESS_SESSION_EXPIRATION: 720h
    SENSE_INGRESS_REDIS_ADDRS: "http://redis_master.{{ .Release.Namespace | default "sense" }}.svc.cluster.local:6397"
    SENSE_INGRESS_REDIS_MASTER_INGRESS_USE_AUTHENTICATION: "true"
    SENSE_INGRESS_REGISTRAR: sql
    SENSE_INGRESS_DOCUMENT_ENABLED_STORES: tsdb
    SENSE_INGRESS_EMAIL_SENDER: no-reply@sixgill.com
    SENSE_INGRESS_SQL_RUN_SETUP: "false"
    GOOGLE_PROJECT_ID: sixgill
    SENSE_INGRESS_BG_AUTOLABEL_SERVICE: "http://autolabel.{{ .Release.Namespace | default "sense" }}.svc.cluster.local:8080"
    SENSE_INGRESS_BG_AUTOLABEL_TIMEOUT: 30s
    SENSE_INGRESS_BG_DEBUG: "true"  
    SENSE_INGRESS_SQL_DIALECT: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrator
  namespace: {{ .Release.Namespace | default "sense" }}
data:
  SENSE_INGRESS_SQL_DIALECT: postgres