---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: migrator
    job-name: migrator
  name: migrator
  namespace: {{ .Release.Namespace | default "sense" }}
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: migrator
        job-name: migrator
    spec:
      containers:
      - args:
        - -c
        - /bin/migrator -skip-es=false; curl -s -X POST http://127.0.0.1:15020/quitquitquit
        command:
        - /bin/bash
        envFrom:
        - configMapRef:
            name: migrator
        env:
        - name: SENSE_INGRESS_SQL_URL
          valueFrom:
            secretKeyRef:
              key: SENSE_INGRESS_SQL_URL
              name: sense-secret
        {{ if .Values.sense }}
        {{ if .Values.sense.migrator }}
        image: "{{ .Values.sense.migrator.registry }}/{{ .Values.sense.migrator.repo }}:{{ .Values.sense.migrator.tag }}"
        {{ else }}
        image: "gcr.io/sense-artifacts/marketplace/migrator:latest"
        {{ end }}
        {{ else }}
        image: "gcr.io/sense-artifacts/marketplace/migrator:latest"
        {{ end }}
        imagePullPolicy: Always
        name: migrator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{ if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{ range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{ end }}
      {{ end }}
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30